// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cache.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fca3b110c9bbf3a, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Key struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Key) Reset()         { *m = Key{} }
func (m *Key) String() string { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()    {}
func (*Key) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fca3b110c9bbf3a, []int{1}
}

func (m *Key) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Key.Unmarshal(m, b)
}
func (m *Key) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Key.Marshal(b, m, deterministic)
}
func (m *Key) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key.Merge(m, src)
}
func (m *Key) XXX_Size() int {
	return xxx_messageInfo_Key.Size(m)
}
func (m *Key) XXX_DiscardUnknown() {
	xxx_messageInfo_Key.DiscardUnknown(m)
}

var xxx_messageInfo_Key proto.InternalMessageInfo

func (m *Key) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type T struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *T) Reset()         { *m = T{} }
func (m *T) String() string { return proto.CompactTextString(m) }
func (*T) ProtoMessage()    {}
func (*T) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fca3b110c9bbf3a, []int{2}
}

func (m *T) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_T.Unmarshal(m, b)
}
func (m *T) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_T.Marshal(b, m, deterministic)
}
func (m *T) XXX_Merge(src proto.Message) {
	xxx_messageInfo_T.Merge(m, src)
}
func (m *T) XXX_Size() int {
	return xxx_messageInfo_T.Size(m)
}
func (m *T) XXX_DiscardUnknown() {
	xxx_messageInfo_T.DiscardUnknown(m)
}

var xxx_messageInfo_T proto.InternalMessageInfo

func (m *T) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type KeyValue struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                *T       `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyValue) Reset()         { *m = KeyValue{} }
func (m *KeyValue) String() string { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()    {}
func (*KeyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fca3b110c9bbf3a, []int{3}
}

func (m *KeyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyValue.Unmarshal(m, b)
}
func (m *KeyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyValue.Marshal(b, m, deterministic)
}
func (m *KeyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyValue.Merge(m, src)
}
func (m *KeyValue) XXX_Size() int {
	return xxx_messageInfo_KeyValue.Size(m)
}
func (m *KeyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyValue.DiscardUnknown(m)
}

var xxx_messageInfo_KeyValue proto.InternalMessageInfo

func (m *KeyValue) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyValue) GetValue() *T {
	if m != nil {
		return m.Value
	}
	return nil
}

type KeyValueTtl struct {
	Key                  string             `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                *T                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Ttl                  *duration.Duration `protobuf:"bytes,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *KeyValueTtl) Reset()         { *m = KeyValueTtl{} }
func (m *KeyValueTtl) String() string { return proto.CompactTextString(m) }
func (*KeyValueTtl) ProtoMessage()    {}
func (*KeyValueTtl) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fca3b110c9bbf3a, []int{4}
}

func (m *KeyValueTtl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyValueTtl.Unmarshal(m, b)
}
func (m *KeyValueTtl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyValueTtl.Marshal(b, m, deterministic)
}
func (m *KeyValueTtl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyValueTtl.Merge(m, src)
}
func (m *KeyValueTtl) XXX_Size() int {
	return xxx_messageInfo_KeyValueTtl.Size(m)
}
func (m *KeyValueTtl) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyValueTtl.DiscardUnknown(m)
}

var xxx_messageInfo_KeyValueTtl proto.InternalMessageInfo

func (m *KeyValueTtl) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyValueTtl) GetValue() *T {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *KeyValueTtl) GetTtl() *duration.Duration {
	if m != nil {
		return m.Ttl
	}
	return nil
}

type TtlRequest struct {
	Key                  string               `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Stamp                *timestamp.Timestamp `protobuf:"bytes,2,opt,name=stamp,proto3" json:"stamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TtlRequest) Reset()         { *m = TtlRequest{} }
func (m *TtlRequest) String() string { return proto.CompactTextString(m) }
func (*TtlRequest) ProtoMessage()    {}
func (*TtlRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fca3b110c9bbf3a, []int{5}
}

func (m *TtlRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TtlRequest.Unmarshal(m, b)
}
func (m *TtlRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TtlRequest.Marshal(b, m, deterministic)
}
func (m *TtlRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TtlRequest.Merge(m, src)
}
func (m *TtlRequest) XXX_Size() int {
	return xxx_messageInfo_TtlRequest.Size(m)
}
func (m *TtlRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TtlRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TtlRequest proto.InternalMessageInfo

func (m *TtlRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *TtlRequest) GetStamp() *timestamp.Timestamp {
	if m != nil {
		return m.Stamp
	}
	return nil
}

type TtlResponse struct {
	Ttl                  *duration.Duration `protobuf:"bytes,1,opt,name=ttl,proto3" json:"ttl,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *TtlResponse) Reset()         { *m = TtlResponse{} }
func (m *TtlResponse) String() string { return proto.CompactTextString(m) }
func (*TtlResponse) ProtoMessage()    {}
func (*TtlResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fca3b110c9bbf3a, []int{6}
}

func (m *TtlResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TtlResponse.Unmarshal(m, b)
}
func (m *TtlResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TtlResponse.Marshal(b, m, deterministic)
}
func (m *TtlResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TtlResponse.Merge(m, src)
}
func (m *TtlResponse) XXX_Size() int {
	return xxx_messageInfo_TtlResponse.Size(m)
}
func (m *TtlResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TtlResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TtlResponse proto.InternalMessageInfo

func (m *TtlResponse) GetTtl() *duration.Duration {
	if m != nil {
		return m.Ttl
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "pb.Empty")
	proto.RegisterType((*Key)(nil), "pb.Key")
	proto.RegisterType((*T)(nil), "pb.T")
	proto.RegisterType((*KeyValue)(nil), "pb.KeyValue")
	proto.RegisterType((*KeyValueTtl)(nil), "pb.KeyValueTtl")
	proto.RegisterType((*TtlRequest)(nil), "pb.TtlRequest")
	proto.RegisterType((*TtlResponse)(nil), "pb.TtlResponse")
}

func init() { proto.RegisterFile("cache.proto", fileDescriptor_5fca3b110c9bbf3a) }

var fileDescriptor_5fca3b110c9bbf3a = []byte{
	// 360 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xcf, 0x6b, 0xe2, 0x40,
	0x14, 0xc7, 0x8d, 0x21, 0xba, 0xbe, 0x2c, 0xbb, 0xcb, 0xb0, 0xa0, 0x66, 0xc1, 0x95, 0x61, 0x17,
	0xa4, 0x85, 0x28, 0xf6, 0xd4, 0xde, 0x84, 0x16, 0x0f, 0x5e, 0x4a, 0x0c, 0xed, 0x39, 0x31, 0x53,
	0x0d, 0x9d, 0x38, 0xa9, 0x79, 0x11, 0xf2, 0xc7, 0x17, 0xca, 0xcc, 0x24, 0x51, 0x6b, 0x0f, 0xed,
	0x6d, 0x26, 0xdf, 0x1f, 0xf3, 0xde, 0x27, 0x60, 0xaf, 0x82, 0xd5, 0x86, 0xb9, 0xe9, 0x4e, 0xa0,
	0x20, 0xcd, 0x34, 0x74, 0x06, 0x6b, 0x21, 0xd6, 0x9c, 0x8d, 0xd5, 0x97, 0x30, 0x7f, 0x1a, 0x47,
	0xf9, 0x2e, 0xc0, 0x58, 0x6c, 0xb5, 0xc7, 0xf9, 0xfb, 0x5e, 0xc7, 0x38, 0x61, 0x19, 0x06, 0x49,
	0xaa, 0x0d, 0xb4, 0x0d, 0xd6, 0x5d, 0x92, 0x62, 0x41, 0xbb, 0x60, 0x2e, 0x58, 0x41, 0x7e, 0x81,
	0xf9, 0xcc, 0x8a, 0x9e, 0x31, 0x34, 0x46, 0x1d, 0x4f, 0x1e, 0x69, 0x1f, 0x0c, 0x9f, 0xfc, 0x06,
	0x6b, 0x1f, 0xf0, 0x9c, 0x95, 0x82, 0xbe, 0xd0, 0x6b, 0xf8, 0xb6, 0x60, 0xc5, 0x83, 0x3c, 0x9f,
	0x07, 0xc9, 0x9f, 0x2a, 0xd3, 0x1c, 0x1a, 0x23, 0x7b, 0x6a, 0xb9, 0x69, 0xe8, 0xfa, 0x55, 0x34,
	0x06, 0xbb, 0x8a, 0xfa, 0xc8, 0xbf, 0x98, 0x26, 0x97, 0x60, 0x22, 0xf2, 0x9e, 0xa9, 0xa4, 0xbe,
	0xab, 0x97, 0x74, 0xab, 0x25, 0xdd, 0xdb, 0x12, 0x82, 0x27, 0x5d, 0xf4, 0x1e, 0xc0, 0x47, 0xee,
	0xb1, 0x97, 0x9c, 0x65, 0xf8, 0xc1, 0x4b, 0x13, 0xb0, 0x14, 0x91, 0xf2, 0x25, 0xe7, 0xac, 0xce,
	0xaf, 0x98, 0x79, 0xda, 0x48, 0x6f, 0xc0, 0x56, 0x8d, 0x59, 0x2a, 0xb6, 0x59, 0x3d, 0x8d, 0xf1,
	0x99, 0x69, 0xa6, 0xaf, 0x06, 0xb4, 0x97, 0x28, 0x76, 0xc1, 0x9a, 0x91, 0x21, 0x98, 0xb3, 0x28,
	0x22, 0xdf, 0xe5, 0x6e, 0x15, 0x0d, 0xa7, 0x23, 0x6f, 0xfa, 0x9f, 0x34, 0x48, 0x17, 0xcc, 0x39,
	0x43, 0xd2, 0x2e, 0x1d, 0x8e, 0xc6, 0x40, 0x1b, 0x64, 0x00, 0xad, 0x39, 0xc3, 0x19, 0xe7, 0xe4,
	0xe0, 0xaf, 0xd5, 0x89, 0x21, 0x75, 0x8f, 0x25, 0x62, 0xcf, 0x0e, 0xd9, 0x93, 0xe2, 0x0b, 0x80,
	0x59, 0x14, 0x3d, 0xc6, 0xb8, 0x91, 0xf8, 0x7f, 0x1e, 0x4f, 0xe0, 0x23, 0x3f, 0xf5, 0xfe, 0x53,
	0x6f, 0x49, 0x5f, 0xdd, 0xa5, 0x02, 0x47, 0x0c, 0x68, 0x83, 0xfc, 0x87, 0xd6, 0x52, 0xbb, 0x7e,
	0xd4, 0xa2, 0x42, 0x7e, 0x52, 0x16, 0xb6, 0x14, 0x97, 0xab, 0xb7, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x14, 0x39, 0x23, 0x88, 0xcb, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StorageClient is the client API for Storage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StorageClient interface {
	Add(ctx context.Context, in *KeyValue, opts ...grpc.CallOption) (*Empty, error)
	Get(ctx context.Context, in *Key, opts ...grpc.CallOption) (*T, error)
	GetAll(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Storage_GetAllClient, error)
	Remove(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Empty, error)
	AddWithTtl(ctx context.Context, in *KeyValueTtl, opts ...grpc.CallOption) (*Empty, error)
	GetTtl(ctx context.Context, in *Key, opts ...grpc.CallOption) (*TtlResponse, error)
	SetTtl(ctx context.Context, in *TtlRequest, opts ...grpc.CallOption) (*Empty, error)
}

type storageClient struct {
	cc *grpc.ClientConn
}

func NewStorageClient(cc *grpc.ClientConn) StorageClient {
	return &storageClient{cc}
}

func (c *storageClient) Add(ctx context.Context, in *KeyValue, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.Storage/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) Get(ctx context.Context, in *Key, opts ...grpc.CallOption) (*T, error) {
	out := new(T)
	err := c.cc.Invoke(ctx, "/pb.Storage/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetAll(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Storage_GetAllClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Storage_serviceDesc.Streams[0], "/pb.Storage/GetAll", opts...)
	if err != nil {
		return nil, err
	}
	x := &storageGetAllClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Storage_GetAllClient interface {
	Recv() (*T, error)
	grpc.ClientStream
}

type storageGetAllClient struct {
	grpc.ClientStream
}

func (x *storageGetAllClient) Recv() (*T, error) {
	m := new(T)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *storageClient) Remove(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.Storage/Remove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) AddWithTtl(ctx context.Context, in *KeyValueTtl, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.Storage/AddWithTtl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetTtl(ctx context.Context, in *Key, opts ...grpc.CallOption) (*TtlResponse, error) {
	out := new(TtlResponse)
	err := c.cc.Invoke(ctx, "/pb.Storage/GetTtl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) SetTtl(ctx context.Context, in *TtlRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.Storage/SetTtl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServer is the server API for Storage service.
type StorageServer interface {
	Add(context.Context, *KeyValue) (*Empty, error)
	Get(context.Context, *Key) (*T, error)
	GetAll(*Empty, Storage_GetAllServer) error
	Remove(context.Context, *Key) (*Empty, error)
	AddWithTtl(context.Context, *KeyValueTtl) (*Empty, error)
	GetTtl(context.Context, *Key) (*TtlResponse, error)
	SetTtl(context.Context, *TtlRequest) (*Empty, error)
}

// UnimplementedStorageServer can be embedded to have forward compatible implementations.
type UnimplementedStorageServer struct {
}

func (*UnimplementedStorageServer) Add(ctx context.Context, req *KeyValue) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (*UnimplementedStorageServer) Get(ctx context.Context, req *Key) (*T, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedStorageServer) GetAll(req *Empty, srv Storage_GetAllServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (*UnimplementedStorageServer) Remove(ctx context.Context, req *Key) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Remove not implemented")
}
func (*UnimplementedStorageServer) AddWithTtl(ctx context.Context, req *KeyValueTtl) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddWithTtl not implemented")
}
func (*UnimplementedStorageServer) GetTtl(ctx context.Context, req *Key) (*TtlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTtl not implemented")
}
func (*UnimplementedStorageServer) SetTtl(ctx context.Context, req *TtlRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetTtl not implemented")
}

func RegisterStorageServer(s *grpc.Server, srv StorageServer) {
	s.RegisterService(&_Storage_serviceDesc, srv)
}

func _Storage_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Storage/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).Add(ctx, req.(*KeyValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Storage/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).Get(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_GetAll_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StorageServer).GetAll(m, &storageGetAllServer{stream})
}

type Storage_GetAllServer interface {
	Send(*T) error
	grpc.ServerStream
}

type storageGetAllServer struct {
	grpc.ServerStream
}

func (x *storageGetAllServer) Send(m *T) error {
	return x.ServerStream.SendMsg(m)
}

func _Storage_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Storage/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).Remove(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_AddWithTtl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyValueTtl)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).AddWithTtl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Storage/AddWithTtl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).AddWithTtl(ctx, req.(*KeyValueTtl))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_GetTtl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).GetTtl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Storage/GetTtl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).GetTtl(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_SetTtl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TtlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).SetTtl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Storage/SetTtl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).SetTtl(ctx, req.(*TtlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Storage_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Storage",
	HandlerType: (*StorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _Storage_Add_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Storage_Get_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _Storage_Remove_Handler,
		},
		{
			MethodName: "AddWithTtl",
			Handler:    _Storage_AddWithTtl_Handler,
		},
		{
			MethodName: "GetTtl",
			Handler:    _Storage_GetTtl_Handler,
		},
		{
			MethodName: "SetTtl",
			Handler:    _Storage_SetTtl_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAll",
			Handler:       _Storage_GetAll_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cache.proto",
}
